"""调整列。

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a7f6b9f900b"
down_revision: str | None = "893b5792bdcd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级 schema。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chats") as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Text(), nullable=True))
        batch_op.create_index(
            "idx_chats_user_id",
            ["user_id"],
            unique=False,
            postgresql_using="hash",
        )
        batch_op.create_foreign_key(
            "fk_chats_user_id",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
    with op.batch_alter_table("messages") as batch_op:
        batch_op.alter_column("files", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级 schema。"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages") as batch_op:
        batch_op.alter_column("files", existing_type=sa.TEXT(), nullable=True)
    with op.batch_alter_table("chats") as batch_op:
        batch_op.drop_constraint("fk_chats_user_id", type_="foreignkey")
        batch_op.drop_index("idx_chats_user_id", postgresql_using="hash")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
